config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  post 'stats/tweet'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')

  get 'i/signout', to: 'sessions#destroy', as: 'signout'
  get 'i/follow', to: 'sessions#follow', as: 'follow_us'
  post 'i/follow', to: 'sessions#follow_me', as: 'follow'

  mount Sidekiq::Web, at: '/notsecure/sidekiq'

  get ':username', to: 'stats#username', as: :username

  root 'pages#index'

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user
  serialize :params

  validates_uniqueness_of :tid
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :tweets
  serialize :twitter_params

  def twitter
    @client ||= Twitter::REST::Client.new do |config|
      config.consumer_key        = ENV["TWITTER_KEY"]
      config.consumer_secret     = ENV["TWITTER_SECRET"]
      config.access_token        = token
      config.access_token_secret = secret
    end
  end

  def source_stats
    tweets.group(:source).count
  end

  def self.find_or_create_from_auth_hash(auth)
    user = where(provider: auth.provider, uid: auth.uid).first 
    if user
      user.update twitter_params: auth
    else  
      return create_from_omniauth(auth)
    end
    user
  end

  def self.create_from_omniauth(auth)
    user = create! do |u|
      u.provider = auth["provider"]
      u.uid = auth["uid"]
      u.handle = auth["info"]["nickname"].downcase
      u.token = auth["credentials"]["token"]
      u.secret = auth["credentials"]["secret"]
      u.last_calculated_at = Time.now
      u.twitter_params = auth
    end
    FetchSourceJob.perform_later user.id
    user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    if current_user
      redirect_to username_path(username: current_user.handle)
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_or_create_from_auth_hash(env["omniauth.auth"])
    session[:user_id] = user.id

    if user.last_calculated_at < 24.hours.ago
      FetchSourceJob.perform_later user.id
    end
    redirect_to follow_us_path, notice: "Signed in!"
  end

  def follow
    @user = current_user
  end

  def follow_me
    FollowMeJob.perform_later current_user.id
    redirect_to username_path(username: current_user.handle)
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Signed out!"
  end

end

app/controllers/stats_controller.rb
class StatsController < ApplicationController
  def username
    @handle = params[:username].downcase
    @user = User.where(handle: @handle).first

    unless @user
      render "stats/not_found"
      return
    end

    @sources = @user.source_stats.select { |k, v| k }.map { |k, v| { source: k, count: v, source_name: /<a(.*)>(.*)<\/a>/.match(k)[2] } }.sort_by { |e| e[:count] }.reverse

    if @user.last_calculated_at < 2.days.ago
      FetchSourceJob.perform_later @user.id
      @user.last_calculated_at = 2.seconds.ago
      @user.save
    end

    respond_to do |format|
      format.html
      format.json { render json: @sources }
    end
  end

  def tweet
    text = params[:tweet]

    SendTweetJob.perform_later current_user.id, text

    respond_to do |format|
      format.js
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/stats_helper.rb
module StatsHelper
end

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-default{ role: "navigation" }
  .navbar-header
    %button.navbar-toggle{ type: "button", data: { toggle: "collapse", target: "#navbar-link" } }
      %span.sr-only Toggle Navigation
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    %a.navbar-brand{ href: root_url } Tweetinators!
  .collapse.navbar-collapse#navbar-link
    %ul.nav.navbar-nav
      - if current_user
        %li= link_to "Sign out", "/i/signout"
      - else
        %li= link_to "Sign in with Twitter", "/auth/twitter"

app/views/layouts/_sponsor.html.haml
.row
  .col-lg-10.col-lg-offset-1
    %small.text-warning This week has been sponsored by :-
    %h3 Mask your email and block all the spam
    %p.lead
      %a{ href: "http://www.getid.in/?utm_source=Tweetinators&utm_campaign=WeekSponsor&utm_medium=#{handle}-handle" } Try getid.in!
    .embed-responsive.embed-responsive-16by9
      %iframe.embed-responsive-item{ src: "https://www.youtube.com/embed/npdMTr6juhQ", allowfullscreen: true }
    %hr
    %small
      If you'd like to sponsor a week's worth of life for Tweetinators,
      %a{ href: "https://twitter.com/shobhitic" } contact me.

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
  %head
    %title
      = yield(:title).presence || "Tweetinator"
    = stylesheet_link_tag    '//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css', media: 'all'
    = stylesheet_link_tag    "//maxcdn.bootstrapcdn.com/bootswatch/3.3.2/journal/bootstrap.min.css"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    = yield(:head)
  %body
    = render 'layouts/navbar'
    - if notice
      %p.alert.alert-info= notice
    .container= yield
    %footer.footer
      .container
        .center
          %p.text-muted
            Horribly designed and created by
            = link_to "@shobhitic", "https://twitter.com/shobhitic"

app/views/pages/index.html.haml
.center
  %h1 Find the apps you've used to tweet
  %h3 ... and what others have been using to tweet!

%hr

.row
  .col-md-8.col-md-offset-2
    %p
      Probably a useless app which gives a web page telling which apps you've used to tweet. Some people are telling it is super fun to see those metrics. Some say it is probably the best thing since sliced bread. So what are you waiting for?


.center
  %a.btn.btn-info.btn-lg{ href: '/auth/twitter' }
    %i.fa.fa-twitter.fa-lg
    Sign in using Twitter

.row.down-50
  .col-md-6
    .container-fluid
      .row
        .col-md-2
          = image_tag "https://pbs.twimg.com/profile_images/496872646479319040/zLNF4x_W_400x400.jpeg", class: "img-responsive img-circle", height: "75px", width: "75px"
        .col-md-10
          %blockquote
            It is super fun to see those metrics.
            %footer
              = link_to "@deepak365", username_path("deepak365")
  .col-md-6
    .container-fluid
      .row
        .col-md-2
          = image_tag "https://pbs.twimg.com/profile_images/533922086738079745/Cy-uoICm_400x400.jpeg", class: "img-responsive img-circle"
        .col-md-10
          %blockquote
            Probably the best thing since sliced bread.
            %footer
              = link_to "@ispiritualist", username_path("ispiritualist")
  .col-md-6
    .container-fluid
      .row
        .col-md-2
          = image_tag "https://pbs.twimg.com/profile_images/567619491698204672/h-HRu48G_400x400.jpeg", class: "img-responsive img-circle"
        .col-md-10
          %blockquote
            Twitter just died for me. No need to visit it anymore!
            %footer
              = link_to "@shotwhat", username_path("shotwhat")
  .col-md-6
    .container-fluid
      .row
        .col-md-2
          = image_tag "https://pbs.twimg.com/profile_images/544025497227640833/PPiTt2O__400x400.jpeg", class: "img-responsive img-circle"
        .col-md-10
          %blockquote
            How do you know what devices I own? How did you hack in to them?
            %footer
              = link_to "@jub_in", username_path("jub_in")

app/views/stats/not_found.html.haml
.row
  .center
    %h2
      Stats for @#{@handle} not found!
    %hr
  - if current_user
    #tweet-prompt
      .col-lg-offset-1.col-lg-9
        .alert.alert-success
          %p
            Hey @#{@handle}, I'd like to see your tweeting stats! Simply sign in at tweetinators.com and tweet your stats page!
      .col-lg-2
        = button_to stats_tweet_path(tweet: "Hey @#{@handle}, I'd like to see your tweeting stats! Simply sign in at tweetinators.com and tweet your stats page!"), class: "btn btn-lg btn-info pull-right", remote: true do
          %i.fa.fa-twitter.fa-lg
          Tweet
  .col-lg-6.col-lg-offset-3{ style: "margin-top: 30px; margin-bottom: 30px" }
    %p
      I am sorry, but I couldn't find any data about #{@handle} in our system. If you'd like to see their stats, send them a tweet so they'd sign up! :)
    %img.img-responsive{ src: "http://i.imgur.com/5B0qeix.jpg" }

app/views/stats/tweet.js.erb
$('#tweet-prompt').html('<p class="text-center lead">Thanks for spreading the love! :)</p>');

app/views/stats/username.html.haml
- content_for :head do
  = javascript_include_tag 'Chart'
- content_for :title, "This is how @#{@user.handle} tweets!"


.page-header
  .row
    .col-lg-6
      .container-fluid.center
        .row
          - if @user.twitter_params
            .profile-img= image_tag @user.twitter_params[:info][:image].sub(/_normal\.jpeg/, "_400x400.jpeg"), class: "img-circle", width: "200px"
        .row
          %h1.handle= link_to "@#{@user.handle}", "https://twitter.com/#{@user.handle}"
        .row
          - if @user.twitter_params
            %p.lead= @user.twitter_params[:info][:description]
    .col-lg-6.sources-chart
      = content_tag "div", id: "usernames", data: { sources: @sources, handle: @user.handle } do
        .center
          %p.lead
            Loading chart...
      %canvas.chart

- if current_user && current_user.id == @user.id
  .row#tweet-prompt
    .col-lg-offset-1
      %p.lead Tweet your stats!
    .col-lg-offset-1.col-lg-9
      .alert.alert-success
        %p
          %strong Look at how I tweet! tweetinators.com/#{@user.handle} #tweetinators
    .col-lg-2
      = button_to stats_tweet_path(tweet: "Look at how I tweet! tweetinators.com/#{@user.handle} #tweetinators"), class: "btn btn-lg btn-info pull-right", remote: true do
        %i.fa.fa-twitter.fa-lg
        Tweet
    
.row
  .col-lg-6.sources-list
    .list-group
      - @sources.each do |source|
        .list-group-item
          %span.badge= source[:count]
          = source[:source].html_safe
  .col-lg-6
    .container-fluid
      = render "layouts/sponsor", handle: @user.handle
    